modLoader = "javafml"
loaderVersion = "[1,)"
license = "MPL-2.0"

[[mods]]
modId = "upgradablegaps"
version = "${version}"
displayName = "Upgradable Gaps"
authors = "Tyler Fursman"
description = '''Upgrade a golden apple into an enchanted golden apple with 8 gold ingots in each surrounding slot. Server-side; vanilla clients can join.'''

[[mixins]]
config = "upgradablegaps.mixins.json"

[[dependencies.upgradablegaps]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_range}"
ordering = "NONE"
side = "BOTH"
