# Copyright (c) 2026 Tyler Fursman
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

modLoader = "javafml"
loaderVersion = "[1,)"
license = "MPL-2.0"

[[mods]]
modId = "upgradablegaps"
version = "${version}"
displayName = "Upgradable Gaps"
authors = "Tyler Fursman"
description = '''Upgrade a golden apple into an enchanted golden apple with 8 gold ingots in each surrounding slot. Server-side; vanilla clients can join.'''
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.upgradablegaps]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.upgradablegaps]]
modId = "forge"
mandatory = true
versionRange = "${forge_range}"
ordering = "NONE"
side = "BOTH"
