# Copyright (c) 2026 Tyler Fursman
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

loom.platform=neoforge
minecraft_version=26.3
java_version=25
menu=1.21.2
slot=1.17
game_versions=26.1,26.1.1,26.1.2,26.2,26.3
minecraft_range=[26.1,27)
neoforge_version=26.3.0.10-beta
