# Copyright (c) 2026 Tyler Fursman
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

mod_version=1.0.0
fabric_loader_version=0.19.5
