# Copyright (c) 2026 Tyler Fursman
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

loom.platform=fabric
minecraft_version=1.21.11
java_version=21
menu=1.21.2
slot=1.17
game_versions=1.21.2,1.21.3,1.21.4,1.21.5,1.21.6,1.21.7,1.21.8,1.21.9,1.21.10,1.21.11
minecraft_range=>=1.21.2 <26.1
